### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by nyebo**
I had a problem in 'tags'.

ex) https://nyebo.github.iotags/syntax

I add '/' between {{ $baseurl }} and {{ $data.Plural }}.

so, It's OK now.

### CODE REVIEW

**Comment by nelsonjchen** [comment]
I think this might be a regression. The fix was to append a `/` to your baseurl setting, not the theme. 

I host my site on S3 and this change adds an _extra_ slash which causes my tags to not work. The double `/` is ignored for `hugo server`, github pages, and probably other traditional web services but on S3 static hosting and friends, a double slash is fatal. From the `hugo` documentation, [the usual format of the `baseurl` includes a postfix of `/`](https://gohugo.io/overview/configuration/).

**Comment by nelsonjchen** [comment]
Here's the page on my site where it is failing. 

https://mindflakes.com/tags/index.html

**Comment by nyebo** [comment]
Thanks. I fix the `baseurl` as yours. It works.
I'm sorry to jump to conclusions.
how do i undo a commit? what I need to do?

**Comment by enten** [comment]
Thanks Nelson. It was a regression. I revert [it](https://github.com/enten/hyde-y/pull/11).

**Pull request merged**
